In [1]:
import pandas as pd
import numpy as np

In [2]:
male =  pd.read_excel("../data/raw/male_data.xlsx")
female = pd.read_excel("../data//raw/female_data.xlsx")

In [3]:
male.head()

,KODE_SAMPEL,JK,USIA,CT1,CT2,CT3,CT4,CT5,CT6,CT7,...,GS9,GS10,GS11,GS12,GS13,GS14,GS15,citra_tubuh,aktivitas_fisik,gizi_seimbang
0,PH82,Male,13,1,5,4,4,4,4,1,...,4,5,5,3,3,3,3,3,3,3
1,PH84,Male,13,3,2,4,1,3,3,4,...,4,2,4,5,3,3,3,3,3,3
2,PH85,Male,13,4,2,3,4,3,5,5,...,3,3,4,4,5,3,1,3,3,4
3,PH86,Male,13,3,2,3,2,3,4,4,...,3,3,4,4,3,3,2,3,2,3
4,PH87,Male,14,4,1,2,3,4,3,4,...,3,4,3,3,2,3,3,3,3,3

In [9]:
# Tidak perlu membuat slice terpisah
cols = ["citra_tubuh", "aktivitas_fisik", "gizi_seimbang"]
mapping = {1: "Rendah", 2: "Rendah", 3: "Sedang", 4: "Tinggi", 5: "Tinggi"}

for col in cols:
    male[f'{col}_cat'] = male[col].map(mapping).astype('object')
    male[f'{col}_cat'] = pd.Categorical(
        male[f'{col}_cat'],
        categories=["Rendah", "Sedang", "Tinggi"],
        ordered=True
    )

male

,KODE_SAMPEL,JK,USIA,CT1,CT2,CT3,CT4,CT5,CT6,CT7,...,GS12,GS13,GS14,GS15,citra_tubuh,aktivitas_fisik,gizi_seimbang,citra_tubuh_cat,aktivitas_fisik_cat,gizi_seimbang_cat
0,PH82,Male,13,1,5,4,4,4,4,1,...,3,3,3,3,3,3,3,Sedang,Sedang,Sedang
1,PH84,Male,13,3,2,4,1,3,3,4,...,5,3,3,3,3,3,3,Sedang,Sedang,Sedang
2,PH85,Male,13,4,2,3,4,3,5,5,...,4,5,3,1,3,3,4,Sedang,Sedang,Tinggi
3,PH86,Male,13,3,2,3,2,3,4,4,...,4,3,3,2,3,2,3,Sedang,Rendah,Sedang
4,PH87,Male,14,4,1,2,3,4,3,4,...,3,2,3,3,3,3,3,Sedang,Sedang,Sedang
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,SG915,Male,15,3,5,5,1,4,4,5,...,2,5,5,3,4,3,3,Tinggi,Sedang,Sedang
789,SG916,Male,14,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,Rendah,Rendah,Rendah
790,SG918,Male,14,3,5,5,3,3,4,4,...,4,4,4,3,3,3,3,Sedang,Sedang,Sedang
791,SG919,Male,14,3,4,4,2,3,3,4,...,2,2,2,2,3,3,3,Sedang,Sedang,Sedang
792,SG923,Male,16,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,Sedang,Sedang,Sedang

In [11]:
male_df = male[['citra_tubuh', 'aktivitas_fisik', 'gizi_seimbang', 'citra_tubuh_cat', 'aktivitas_fisik_cat', 'gizi_seimbang_cat']]
male_df.to_excel("../data/processed/male.xlsx", index=False)

In [3]:
# Tidak perlu membuat slice terpisah
cols = ["citra_tubuh", "aktivitas_fisik", "gizi_seimbang"]
mapping = {1: "Rendah", 2: "Rendah", 3: "Sedang", 4: "Tinggi", 5: "Tinggi"}

for col in cols:
    female[f'{col}_cat'] = female[col].map(mapping).astype('object')
    female[f'{col}_cat'] = pd.Categorical(
        female[f'{col}_cat'],
        categories=["Rendah", "Sedang", "Tinggi"],
        ordered=True
    )

female

,KODE_SAMPEL,JK,USIA,CT1,CT2,CT3,CT4,CT5,CT6,CT7,...,GS12,GS13,GS14,GS15,citra_tubuh,aktivitas_fisik,gizi_seimbang,citra_tubuh_cat,aktivitas_fisik_cat,gizi_seimbang_cat
0,PH81,Female,13,3,3,4,3,4,4,3,...,3,2,3,3,3,3,3,Sedang,Sedang,Sedang
1,PH83,Female,13,3,3,4,3,4,5,5,...,3,5,2,4,3,3,3,Sedang,Sedang,Sedang
2,PH89,Female,13,4,3,3,5,3,1,4,...,2,1,2,3,3,3,2,Sedang,Sedang,Rendah
3,PH810,Female,13,3,5,5,1,3,2,2,...,3,3,3,3,3,3,3,Sedang,Sedang,Sedang
4,PH811,Female,12,4,3,3,3,4,4,5,...,4,4,5,3,3,3,3,Sedang,Sedang,Sedang
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,SG925,Female,14,3,3,3,3,3,3,3,...,3,3,5,1,3,3,3,Sedang,Sedang,Sedang
776,SG926,Female,14,3,2,1,4,3,4,4,...,3,5,5,5,3,3,3,Sedang,Sedang,Sedang
777,SG927,Female,14,3,3,3,3,3,3,3,...,5,4,2,2,3,3,3,Sedang,Sedang,Sedang
778,SG928,Female,14,2,3,1,4,3,3,4,...,5,4,5,3,3,3,3,Sedang,Sedang,Sedang
779,SG929,Female,16,5,2,1,4,3,3,4,...,5,4,5,3,3,3,3,Sedang,Sedang,Sedang

In [4]:
female_df = female[['citra_tubuh', 'aktivitas_fisik', 'gizi_seimbang', 'citra_tubuh_cat', 'aktivitas_fisik_cat', 'gizi_seimbang_cat']]
female_df.to_excel("../data/processed/female.xlsx", index=False)

In [ ]:
male.to_excel('../data/male_final.xlsx', index=False)
female.to_excel('../data/female_final.xlsx', index=False)